name: Test GHA Docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GO_VERSION: 1.17
  GOLANGCI_LINT_VERSION: v1.42.1
  GOTESTSUM_VERSION: 1.7.0
  TASK_VERSION: 3.9.0
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: "0"
      - uses: wagoid/commitlint-github-action@v4
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: ${{ env.TASK_VERSION }}
      - name: Verify
        run: |
          task verify
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          skip-go-installation: true
          args: -v
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: "0"
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: ${{ env.TASK_VERSION }}
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: ${{ env.GOTESTSUM_VERSION }}
      - name: Run tests
        run: |
          task test
        continue-on-error: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: github.event_name == 'pull_request'
        with:
          fail_on_failure: true
          report_paths: junit.xml
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.out
          flags: unittests
          name: gha-docs
